name: Discord Notification

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        run: |
          COMMIT_HASH=$(echo "${{ github.event.head_commit.id }}" | cut -c1-7)
          COMMIT_COUNT=$(echo '${{ toJson(github.event.commits) }}' | jq length)
          
          if [ $COMMIT_COUNT -eq 1 ]; then
            COMMIT_WORD="commit"
          else
            COMMIT_WORD="commits"
          fi
          
          curl -H "Content-Type: application/json" \
            -X POST \
            -d @- \
            ${{ secrets.DISCORD_WEBHOOK_URL }} << EOF
          {
            "embeds": [
              {
                "title": "${{ github.repository }}:${{ github.ref_name }}",
                "description": "$COMMIT_COUNT new $COMMIT_WORD",
                "url": "${{ github.event.compare }}",
                "color": 7506394,
                "fields": [
                  {
                    "name": "Latest Commit",
                    "value": "\`$COMMIT_HASH\` ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.author.name }}",
                    "inline": false
                  }
                ]
              }
            ]
          }
          EOF
