name: Discord Notification

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit count
        id: commits
        run: echo "count=$(echo '${{ toJson(github.event.commits) }}' | jq length)" >> $GITHUB_OUTPUT
      
      - name: Discord Notification
        run: |
          COMMIT_HASH=$(echo "${{ github.event.head_commit.id }}" | cut -c1-7)
          
          if [ "${{ steps.commits.outputs.count }}" -eq 1 ]; then
            COMMIT_WORD="commit"
          else
            COMMIT_WORD="commits"
          fi
          
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"content\": \"[\`${{ github.repository }}:${{ github.ref_name }}\`] ${{ steps.commits.outputs.count }} new $COMMIT_WORD\\n\`$COMMIT_HASH\` ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.author.name }}\"
            }" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
